version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: VehiculeMicroService
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vehicule-network

volumes:
  mysql-data:

networks:
  vehicule-network:
